import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Site metadata for SEO and browser
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Set favicon path with repo prefix for GitHub Pages (static, SSR-safe)
  const repo = "ald-chess_club-homepage";
  const faviconPath =
    typeof window !== "undefined" && window.location.hostname.endsWith("github.io")
      ? `/${repo}/images/aldershot_logo.png`
      : "/images/aldershot_logo.png";

  return (
    <html lang="en">
      <head>
        {/* Favicon for browser tab, supports GitHub Pages subdirectory */}
        <link rel="icon" href={faviconPath} type="image/png" />
      </head>
      {/* Main body with custom fonts */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
